## Excepciones

A veces nos podemos encontrar con errores de ejecución en nuestro código y debemos de estar prevenidos. Pueden ser debidos a errores del código y como programadores los iremos corrigiendo, mejorando así la calidad del código.  

También hay errores que se pueden producir por circunstancias externas, como por ejemplo cuando no podemos acceder a un archivo, o cuando hay un problema de acceso a la red que no está disponible. Son lo que se conoce como **errores de tiempo de ejecución** (**Runtime errors** en inglés) y un buen programa siempre tiene que estar protegido contra ellos.

También es necesario proteger nuestros programas contra  el mal uso de los usuarios, que pueden ser mal intencionados o por despiste.

No hay que confundir estos errores con los errores de sintaxis por código mal formado. Existe un mecanismo para tratar estos errores en tiempo de ejecución, cuando nuestro programa se está ejecutando.

Cuando se produce un error de estos decimos que se genera una **excepción**, y cuando se produce una nuestro programa se detiene en esa línea y se para.

Podemos hacer que nuestro código capture estas excepciones y así evitar que nuestro programa finalice. Para ello usaremos la estructura **try: ... except :**, que se divide en 2 partes, a las que llamaremos bloques:

* Ponemos **try:** antes de la parte inicial donde pensamos que se puede producir la excepción. 
* Ponemos **except:** para indicar el código que queremos que se ejecute si se produce la excepción.


Se pueden producir excepciones por ejemplo al hacer operaciones aritméticas, y en este ejemplo vamos a ver cómo podemos reconducir ese error:


```python

try:
    print(1/0)
    # a esta línea nunca se llega....
except:
    print('Se ha producido un error')
# ya fuera    
```

Este programa genera una excepción de tipo **ZeroDivisionError**. Existen muchos tipos diferentes de excepciones.

También se pueden producir errores en la lectura de los sensores, que podemos reconducir. Si no lo hiciéramos el programa se pararía.

Vamos a añadir al programa anterior de lectura del DHT22 tratamiento de excepciones:

```python
import dht
import machine
import time

v = 0.2

dht22 = dht.DHT22(machine.Pin(27))

while True:
    try:
        dht22.measure()
        print('Temperatura: ',dht22.temperature(),'º C  Humedad:',dht22.humidity(),'%')
    except :
        print('Error leyendo el sensor')
    time.sleep()

```

También podemos obtener información del tipo de excepción del siguiente modo:

```python

    try:
        ....
    except Exception as e: # creamos un objeto e con información del error
        print(f'Error: {e}')
```

